<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>2e7e7d0c-7335-4b8d-b188-255966aa7fdd</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BlazorTemplater" Version="1.5.1" />
      <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.3.0" />
    </ItemGroup>

</Project>
